/** Generated by `bun scripts/image-sizes.ts` — intrinsic sizes for explicit width/height attributes. */
export const imageSizes: Record<string, [number, number]> = {
  "/images/at-desk-2023.jpg": [
    1400,
    935
  ],
  "/images/aviation-visit.jpg": [
    1200,
    919
  ],
  "/images/coat-of-arms.png": [
    320,
    271
  ],
  "/images/cutout.png": [
    484,
    515
  ],
  "/images/e-gates-lagos.jpg": [
    1000,
    438
  ],
  "/images/epassport.jpg": [
    704,
    1000
  ],
  "/images/fire-station.jpg": [
    1600,
    889
  ],
  "/images/hero-portrait.jpg": [
    719,
    1500
  ],
  "/images/house-of-reps.jpg": [
    1400,
    933
  ],
  "/images/kuje-custodial.jpg": [
    1400,
    933
  ],
  "/images/leadership-plaque-2025.jpg": [
    1200,
    1089
  ],
  "/images/ministry-logo.png": [
    512,
    512
  ],
  "/images/nameplate.jpg": [
    1400,
    918
  ],
  "/images/ncos-parade.jpg": [
    1400,
    599
  ],
  "/images/nis-hq.jpg": [
    1600,
    735
  ],
  "/images/nis-logo.png": [
    1000,
    400
  ],
  "/images/nscdc-logo.png": [
    512,
    512
  ],
  "/images/nscdc-salute.jpg": [
    1600,
    1064
  ],
  "/images/nta-interview.jpg": [
    1000,
    945
  ],
  "/images/official-portrait-captioned.jpg": [
    719,
    900
  ],
  "/images/official-portrait.jpg": [
    893,
    900
  ],
  "/images/ondo-map.jpg": [
    1280,
    985
  ],
  "/images/ondo-seal.png": [
    511,
    512
  ],
  "/images/podium-speech.jpg": [
    1600,
    1066
  ],
  "/images/portrait-cap.jpg": [
    900,
    675
  ],
  "/images/portrait-crop.jpg": [
    754,
    1000
  ],
  "/images/sectoral-retreat-2026.jpg": [
    1200,
    828
  ],
  "/images/share-card.jpg": [
    1200,
    630
  ],
  "/images/tinubu-portrait.jpg": [
    806,
    900
  ],
  "/images/uk-bilateral.jpg": [
    1600,
    1066
  ],
  "/images/vanguard-award.jpg": [
    1400,
    933
  ]
};
