import type { BlogPost } from './blog'
// Original, dated explainers. Official announcements are attributed, not treated as audited outcomes.
export const journalExpansion: BlogPost[] = [
 {
  slug:'tunji-ojo-national-fire-academy-sheda',title:'Inside the National Fire Academy agenda: training before the emergency',
  excerpt:'Tunji-Ojo’s February 2026 inspection at Sheda put professional training at the centre of the fire-service reform discussion.',
  category:'Public services',image:'podium-speech',date:'2026-09-23',period:'13 February 2026',
  takeaway:'The inspection documented a training project still under construction, alongside a call to strengthen operational readiness.',
  sections:[
   {id:'inspection',title:'An inspection in Sheda',paragraphs:['A Ministry of Interior statement dated 13 February 2026 records Olubunmi Tunji-Ojo’s visit to the National Fire Academy in Sheda, Abuja. The ministry described the project as approximately 65 percent complete at the time. Its planned facilities included classrooms, training grounds, accommodation and a library.'],sources:[0]},
   {id:'training',title:'The emphasis on professional preparation',paragraphs:['The minister’s remarks connected equipment and infrastructure with personnel development. He called for stronger training standards, an improved curriculum and professional discipline. The statement also presented fire prevention as an economic concern because damage to businesses and public assets extends beyond the immediate emergency.'],sources:[0]},
   {id:'next-stage',title:'What would show progress',paragraphs:['For this journal, the useful next questions concern delivery: when facilities become available, how many people train there and how that training reaches operational teams. A construction percentage is a dated project update, not evidence that an academy is fully operational. Future reporting should distinguish buildings completed from courses delivered and improvements in emergency response.']},
  ],sources:[{title:'Ministry of Interior: National Fire Academy inspection',url:'https://interior.gov.ng/dr-tunji-ojo-inspects-national-fire-academy-reaffirms-commitment-to-fire-safety-reform/',date:'13 February 2026'}],relatedPage:{route:'interior',title:'Explore the Interior portfolio'},
 },
 {
  slug:'interior-management-retreat-2026-measuring-results',title:'The 2026 Interior retreat: what measuring results should mean',
  excerpt:'The March 2026 management retreat placed accountability and service delivery at the centre of the ministry’s stated priorities.',
  category:'Institutions',image:'sectoral-retreat-2026',date:'2026-09-23',period:'5 March 2026',
  takeaway:'The retreat set out an accountability agenda; comparable public performance data would show how that agenda develops.',
  sections:[
   {id:'agenda',title:'A renewed focus on performance',paragraphs:['At the Ministry of Interior’s 2026 management retreat, Tunji-Ojo urged the organisation to keep improving rather than regard previous achievements as a finish line. The official account, published on 5 March, describes a meeting focused on service delivery, institutional reform and accountability.'],sources:[0]},
   {id:'coordination',title:'The administrative work behind reform',paragraphs:['Permanent Secretary Magdalene Ajani framed the retreat as an opportunity to examine performance and identify operational gaps. Management and agency leaders were brought together to review indicators and refine plans. The account covered responsibilities ranging from border administration to correctional services and emergency preparedness.'],sources:[0]},
   {id:'evidence',title:'Turning a commitment into an evidence trail',paragraphs:['A useful public scorecard would connect each commitment to a baseline, a deadline and a result. Average processing times, complaint resolution and service availability would help readers understand whether an administrative change affects everyday experience. These are this journal’s suggested measures, not additional targets announced in the statement.','The record is strongest when an announcement can be followed through several reporting periods. This article records what the retreat set out to do; it does not substitute the meeting itself for evidence of completed reform.']},
  ],sources:[{title:'Ministry of Information: accountability, reforms and measurable impact',url:'https://fmino.gov.ng/tunji-ojo-emphasises-accountability-reforms-and-measurable-impact/',date:'5 March 2026'}],relatedPage:{route:'interior',title:'Read the wider reform record'},
 },
 {
  slug:'centralised-passport-personalisation-centre-2025',title:'A closer look at the centralised passport personalisation centre',
  excerpt:'A September 2025 inspection highlighted the production stage of passport reform and an ambitious capacity target.',
  category:'Immigration',image:'at-desk-2023',date:'2026-09-23',period:'18 September 2025',
  takeaway:'Production capacity and the time an applicant waits are different measures; both matter when assessing passport reform.',
  sections:[
   {id:'centre',title:'The September inspection',paragraphs:['The Nigeria Immigration Service reported on 18 September 2025 that Tunji-Ojo and Permanent Secretary Magdalene Ajani inspected its newly built Centralized Passport Personalization Center in Abuja. The service linked the facility to its passport modernisation programme.'],sources:[0]},
   {id:'capacity',title:'Reading the capacity claim carefully',paragraphs:['In that account, the minister described an expected increase in daily passport production from 300 to 5,000 units. That is an attributed capacity claim made during the inspection. The release alone does not establish that the higher figure was subsequently sustained every day or that each application moved through the process without delay.'],sources:[0]},
   {id:'experience',title:'What applicants would want to know',paragraphs:['A production line can be assessed by output and reliability. An applicant experiences the whole journey: a submitted application, the necessary checks, production and collection or delivery. Those stages should not be collapsed into a single number.','Our editorial test for a follow-up is straightforward: compare the announced capacity with dated operating data, then examine the waiting time that applicants actually experience. That would help separate the significance of new infrastructure from the wider work needed to deliver a dependable service.']},
  ],sources:[{title:'Nigeria Immigration Service: inspection of the Centralized Passport Personalization Center',url:'https://immigration.gov.ng/the-comptroller-general-of-immigration-kn-nandap-pcc-mmis-fsmn-received-the-honourable-minister-of-interior-dr-olubunmi-tunji-ojo-and-the-permanent-secretary-ministry-of-interior-dr-magdale/',date:'18 September 2025'}],relatedPage:{route:'interior',title:'Follow the passport and immigration record'},
 },
 {
  slug:'contactless-passport-renewal-rollout-and-reliability',title:'Contactless passport renewal: the rollout and the reliability test',
  excerpt:'Two official updates from 2025 show why a digital service should be judged by both its launch and its response to technical problems.',
  category:'Immigration',image:'e-gates-lagos',date:'2026-09-23',period:'February – September 2025',
  takeaway:'The stated aim was to reduce in-person friction; later technical updates remain part of the same service-delivery record.',
  sections:[
   {id:'rollout',title:'The case for a different process',paragraphs:['An official report dated 6 February 2025 recorded Tunji-Ojo’s announcement that contactless passport renewal would launch in Europe the following day. He presented the change as a way to reduce unnecessary human interaction in the application process. The statement was made during a meeting with the Bureau of Public Procurement.'],sources:[0]},
   {id:'reliability',title:'The operational story continued after launch',paragraphs:['On 29 September 2025, the Nigeria Immigration Service acknowledged technical difficulties experienced by some diaspora applicants using its contactless biometric system. It said work was underway to resolve the problems and described upgrades to the payment gateway. This was a service notice about the position at that time, not a statement that the same problems persist today.'],sources:[1]},
   {id:'assessment',title:'Why both updates belong in the record',paragraphs:['The two releases describe different stages of the same reform: an intended improvement and the practical work of operating it. A balanced account retains both. An online application route is valuable only when people can complete it reliably and obtain help when something fails.','Readers should use current Immigration Service guidance for eligibility, available locations and support. This historical explainer is not an application manual. Future reporting should examine completion rates and resolution times alongside announcements about expansion.']},
  ],sources:[{title:'Ministry of Information: Interior and procurement collaboration',url:'https://fmino.gov.ng/tunji-ojo-reaffirms-interior-ministrys-commitment-to-maintain-internal-security/',date:'6 February 2025'},{title:'Nigeria Immigration Service: contactless passport technical update',url:'https://immigration.gov.ng/nis-addresses-technical-challenges-on-contactless-passport-application-system/',date:'29 September 2025'}],relatedPage:{route:'connect',title:'Find official service contacts'},
 },
 {
  slug:'correctional-education-rehabilitation-2025',title:'Education and rehabilitation in the correctional reform agenda',
  excerpt:'Official accounts from early 2025 linked correctional reform to learning, welfare and the difficult transition back into society.',
  category:'Institutions',image:'bto-kuje-building',date:'2026-09-23',period:'January – February 2025',
  takeaway:'The programme described rehabilitation as a shared responsibility, with education and post-release opportunities central to the discussion.',
  sections:[
   {id:'learning',title:'Learning inside custodial centres',paragraphs:['In its account of a January 2025 ministerial media briefing, the Nigerian Correctional Service highlighted an e-library at Kuje and outlined further work on education and vocational preparation. The same report discussed medical staffing and the challenge of overcrowded facilities. These were elements of the service’s stated programme, rather than a single completed project.'],sources:[0]},
   {id:'partnership',title:'A conversation with civil society',paragraphs:['A separate official statement, published on 13 February 2025, records Tunji-Ojo meeting representatives of Citizens United for the Rehabilitation of Errants. The minister emphasised rehabilitation and reintegration, while the organisation raised educational support and its Books Behind Bars initiative. The discussion also addressed the stigma former inmates can encounter after release.'],sources:[1]},
   {id:'outcomes',title:'Following the individual beyond an announcement',paragraphs:['For editorial follow-up, the important questions are practical: who can take part, what support is available, and whether learning can continue after release. A library, a course and a sustainable route into employment are related but distinct achievements.','These releases give a useful account of priorities and proposed partnerships. To assess results, this journal would look for dated participation and completion figures, access to qualifications, and evidence of continuing support. That approach keeps the focus on people’s experience rather than the number of ceremonies or meetings held.']},
  ],sources:[{title:'Nigerian Correctional Service: 2025 plans and reported achievements',url:'https://www.corrections.gov.ng/news/interior-minister-unveils-2025-plans%2C-commends-ncos-on-key-achievements--%E2%80%A6inmates%E2%80%99-welfare%2C-rehabilitation%2C-and-security-top-the-agenda?news_id=90',date:'28 January 2025'},{title:'Ministry of Information: rehabilitation and transformation of correctional services',url:'https://fmino.gov.ng/fg-reaffirms-commitment-to-rehabilitation-and-transformation-of-correctional-service/',date:'13 February 2025'}],relatedPage:{route:'interior',title:'Explore the correctional-services record'},
 },
 {
  slug:'private-security-quality-regulation-tunji-ojo',title:'Private security: why service quality was the central question',
  excerpt:'A December 2024 meeting with DCAF focused on professional standards and the quality of private security services.',
  category:'Institutions',image:'nameplate',date:'2026-09-23',period:'12 December 2024',
  takeaway:'The discussion placed competence and oversight ahead of simply increasing the number of licensed operators.',
  sections:[
   {id:'meeting',title:'A discussion about standards',paragraphs:['An official report published on 12 December 2024 records Tunji-Ojo’s meeting with a delegation from the Geneva Centre for Security Sector Governance, known as DCAF. The discussion concerned the regulation and professionalisation of private security in Nigeria.'],sources:[0]},
   {id:'quality',title:'The distinction the minister drew',paragraphs:['Tunji-Ojo argued that the value of the sector should be judged by the quality of its services and the competence of operators, rather than the number of companies licensed. The account also records discussion of technology and DCAF’s work with the African Law Foundation on regional legislative engagement.'],sources:[0]},
   {id:'follow-up',title:'How to assess that principle',paragraphs:['The journal’s follow-up questions concern implementation: the training expected of personnel, the consistency of oversight and the ways people can report poor conduct. These questions translate an institutional principle into a service that clients, workers and the wider public can assess.','A meeting establishes a position and a possible direction for cooperation. It does not, by itself, show that standards have changed across a sector. The useful next chapter would document specific measures, when they took effect and what evidence exists of their application.']},
  ],sources:[{title:'Ministry of Information: regulation and professionalisation of private security',url:'https://fmino.gov.ng/dr-tunji-ojo-harps-on-regulation-professionalization-of-private-security-sector/',date:'12 December 2024'}],relatedPage:{route:'interior',title:'Explore institutions under the Interior portfolio'},
 },
 {
  slug:'tunji-ojo-procurement-accountability-2025',title:'Procurement and public service: the systems behind the promise',
  excerpt:'A February 2025 meeting with the Bureau of Public Procurement connected administrative reform with transparency and technology.',
  category:'Institutions',image:'bto-retreat-2024',date:'2026-09-23',period:'6 February 2025',
  takeaway:'A service reform depends on the arrangements behind it as well as the interface that citizens see.',
  sections:[
   {id:'discussion',title:'A conversation about public procurement',paragraphs:['During a meeting with Bureau of Public Procurement Director-General Adebowale Adedokun, Tunji-Ojo called for closer institutional cooperation and stronger procurement accountability. The government’s account was published on 6 February 2025.'],sources:[0]},
   {id:'technology',title:'Technology as an administrative tool',paragraphs:['The minister encouraged the use of technology in procurement and emphasised evaluation and efficiency. The same meeting connected these administrative concerns with the ministry’s responsibilities for services and security.'],sources:[0]},
   {id:'questions',title:'What a useful public record would contain',paragraphs:['Our editorial interest is in the link between a decision and the service it is meant to support. A new system may look simple to the person using it, while depending on contracts, maintenance arrangements and several institutions working together.','A useful follow-up would compare the stated objective with the procurement record and the delivered service. It would ask whether the chosen arrangement solved the original problem and whether responsibilities are clear when something fails. These are questions for evidence-led reporting, not claims that the February meeting established any particular procurement outcome.']},
  ],sources:[{title:'Ministry of Information: Interior Minister receives Bureau of Public Procurement delegation',url:'https://fmino.gov.ng/tunji-ojo-reaffirms-interior-ministrys-commitment-to-maintain-internal-security/',date:'6 February 2025'}],relatedPage:{route:'sources',title:'Read the journal’s source and editorial policy'},
 },
 {
  slug:'tunji-ojo-journalists-public-accountability',title:'The media and the public record: Tunji-Ojo’s meeting with journalists',
  excerpt:'A February 2025 meeting with the NUJ FCT Council raised the relationship between access to officials and public accountability.',
  category:'Public office',image:'official-portrait',date:'2026-09-23',period:'14 February 2025',
  takeaway:'Access is a starting point for reporting. An accountable public record also needs evidence, questions and follow-up.',
  sections:[
   {id:'visit',title:'The February meeting',paragraphs:['On 14 February 2025, the Federal Ministry of Information published an account of Tunji-Ojo receiving the leadership of the Nigeria Union of Journalists, FCT Council. The delegation was led by its chair, Grace Ike.'],sources:[0]},
   {id:'access',title:'The commitment described',paragraphs:['Tunji-Ojo said journalists were welcome to engage with his office and acknowledged the media’s role in holding public officials accountable. The official account records the meeting and the remarks made; it is not an independent assessment of media access across the ministry.'],sources:[0]},
   {id:'journalism',title:'From access to useful reporting',paragraphs:['For this independent journal, a strong article does more than repeat a statement. It identifies when something happened, links to supporting material and makes clear which conclusions are established and which require more evidence.','That distinction matters when reporting on services that affect large numbers of people. An announcement can open a line of inquiry; a later article can examine implementation and ask what changed. Our source lists are intended to make that trail easier to follow, while correction notes explain substantive updates to the published record.']},
  ],sources:[{title:'Ministry of Information: Tunji-Ojo hosts the NUJ FCT Council',url:'https://fmino.gov.ng/tunji-ojo-hosts-nuj/',date:'14 February 2025'}],relatedPage:{route:'sources',title:'How this independent journal uses sources'},
 },
]
