import { readdirSync } from 'node:fs';
const dir = 'public/images';
const out: Record<string, [number, number]> = {};
for (const f of readdirSync(dir).sort()) {
  if (!/\.(jpe?g|png|webp)$/i.test(f)) continue;
  const p = Bun.spawnSync(['sips', '-g', 'pixelWidth', '-g', 'pixelHeight', `${dir}/${f}`]);
  const t = p.stdout.toString();
  const w = Number(/pixelWidth: (\d+)/.exec(t)?.[1]); const h = Number(/pixelHeight: (\d+)/.exec(t)?.[1]);
  if (w && h) out[`/images/${f}`] = [w, h];
}
const src = `/** Generated by \`bun scripts/image-sizes.ts\` — intrinsic sizes for explicit width/height attributes. */\nexport const imageSizes: Record<string, [number, number]> = ${JSON.stringify(out, null, 2)};\n`;
await Bun.write('src/content/imageSizes.ts', src);
console.log(`✓ ${Object.keys(out).length} image sizes written`);
